### ISSUE TITLE
Commands design

### ISSUE THREAD

**Issue by icorbrey** [icorbrey/jjj#95]
I would like to mirror Helix's modal command sets, where the core modes (in `jjj` these will likely be the change log, the operation log, and maybe files?) can each have their own set of keys that map to direct commands, with minor modes that spawn custom menus.

## Example config

```toml
[jjj.keys.change]
j = "move_visual_line_down"
k = "move_visual_line_up"
o = "operation_mode"
"/" = "search"

[jjj.keys.change.space.keys.g]
name = "Git commands..."

[jjj.keys.change.space.keys.g.keys]
f = "git_fetch"
p = "git_push"

[jjj.keys.change.space.keys.g.keys.r]
name = "Remote commands..."

[jjj.keys.change.space.keys.g.keys.r.keys]
a = "git_remote_add"
d = "git_remote_remove"
l = "git_remote_list"
r = "git_remote_rename"

[jjj.keys.operation]
esc = "normal_mode"
```
